#!/bin/sh

node_url="amqp://localhost"
beehive_url="amqps://cookie:23181?auth_mechanism=external&cacertfile=/Users/Sean/github/message-pipeline/ssl/cacert.pem&certfile=/Users/Sean/github/message-pipeline/ssl/cert.pem&keyfile=/Users/Sean/github/message-pipeline/ssl/key.pem&verify=verify_peer"

rabbitmqctl set_parameter shovel shovel-messages-to-beehive "{
\"src-uri\": \"${node_url}\",
\"src-queue\": \"to-beehive\",
\"dest-uri\": \"${beehive_url}\",
\"dest-exchange\": \"messages\"
}"

# rabbitmqctl set_parameter shovel shovel-messages-from-beehive "{
# \"dest-uri\": \"${node_url}\",
# \"dest-queue\": \"messages\",
# \"src-uri\": \"${beehive_url}\",
# \"src-queue\": \"to-node-0000000000000001\"
# }"
