#!/bin/sh

rabbitmqctl set_parameter shovel shovel-messages-to-beehive '{
"src-uri": "amqp://localhost",
"src-queue": "to-beehive",
"dest-uri": "amqps://beehive:23181?auth_mechanism=external&cacertfile=/usr/lib/waggle/SSL/waggleca/cacert.pem&certfile=/usr/lib/waggle/SSL/node/cert.pem&keyfile=/usr/lib/waggle/SSL/node/key.pem&verify=verify_peer",
"dest-exchange": "messages"
}'

rabbitmqctl set_parameter shovel shovel-messages-from-beehive '{
"dest-uri": "amqp://localhost",
"dest-queue": "messages",
"src-uri": "amqps://beehive:23181?auth_mechanism=external&cacertfile=/usr/lib/waggle/SSL/waggleca/cacert.pem&certfile=/usr/lib/waggle/SSL/node/cert.pem&keyfile=/usr/lib/waggle/SSL/node/key.pem&verify=verify_peer",
"src-queue": "to-node-0000000000000001"
}'
