#!/usr/bin/env python3
import pika
import re
from waggle.protocol.v0 import *


node_id = b'node1234'
device_id = b'12345678'


def parse_version_string(s):
    match = re.match(r'(\d+)\.(\d+)\.(\d+)', s)

    if match is None:
        return None

    return tuple(int(n) for n in match.groups())


def parse_plugin_user_id(user_id):
    match = re.match('plugin-([^-]+)-([^-]+)-([^-]+)', user_id)

    if match is None:
        raise ValueError('Invalid plugin user ID.')

    id_string, version_string, instance_string = match.groups()

    return {
        'id': int(id_string, 16),
        'version': parse_version_string(version_string),
        'instance': int(instance_string),
    }


def message_handler(ch, method, properties, body):
    print('---')
    user_id = properties.user_id

    if user_id is None:
        ch.basic_ack(delivery_tag=method.delivery_tag)
        print('Dropping message with missing user ID.', properties, body)
        return

    try:
        plugin_info = parse_plugin_user_id(user_id)
    except ValueError:
        ch.basic_ack(delivery_tag=method.delivery_tag)
        print('Dropping message with invalid plugin user ID.', properties, body)
        return

    for packet in unpack_waggle_packets(body):
        for subpacket in unpack_datagrams(packet['body']):
            data = pack_waggle_packets([
                {
                    'sender_id': node_id,
                    'sender_sub_id': device_id,
                    'receiver_id': packet['receiver_id'],
                    'receiver_sub_id': packet['receiver_sub_id'],
                    'body': pack_datagrams([
                        {
                            'plugin_id': plugin_info['id'],
                            'plugin_major_version': plugin_info['version'][0],
                            'plugin_minor_version': plugin_info['version'][1],
                            'plugin_instance': plugin_info['instance'],
                            'body': subpacket['body'],
                        }
                    ])
                }
            ])

            ch.basic_publish(
              exchange='',
              routing_key='to-beehive',
              properties=pika.BasicProperties(
                delivery_mode=2),
              body=data)

            print('ok', user_id, data)

    ch.basic_ack(delivery_tag=method.delivery_tag)


def main():
    parameters = pika.ConnectionParameters(
        credentials=pika.PlainCredentials(
            username='admin',
            password='admin'),
        virtual_host='node1')

    connection = pika.BlockingConnection(parameters)
    channel = connection.channel()

    channel.exchange_declare(exchange='publish', exchange_type='fanout', durable=True)
    channel.queue_declare(queue='validate', durable=True)
    channel.queue_declare(queue='to-beehive', durable=True)
    channel.queue_bind(exchange='publish', queue='validate')

    channel.basic_consume(message_handler, 'validate')
    channel.start_consuming()


if __name__ == '__main__':
    main()
