#!/usr/bin/env python3
import pika
import re
import time
from waggle.protocol.v0 import *


def parse_version_string(s):
    match = re.match('(\d+)\.(\d+)\.(\d+)', s)

    if match is None:
        return None

    return tuple(int(n) for n in match.groups())


def parse_plugin_user_id(user_id):
    match = re.match('plugin-([^-]+)-([^-]+)-([^-]+)', user_id)

    if match is None:
        raise ValueError('Invalid plugin user ID.')

    id_string, version_string, instance_string = match.groups()

    return {
        'id': int(id_string, 16),
        'version': parse_version_string(version_string),
        'instance': int(instance_string),
    }


def message_handler(ch, method, properties, body):
    print('---')
    user_id = properties.user_id

    if user_id is None:
        ch.basic_ack(delivery_tag=method.delivery_tag)
        print('Dropping message with missing user ID.', properties, body)
        return

    try:
        plugin_info = parse_plugin_user_id(user_id)
    except ValueError:
        ch.basic_ack(delivery_tag=method.delivery_tag)
        print('Dropping message with invalid plugin user ID.', properties, body)
        return

    data = pack_datagrams([
        {
            'plugin_id': plugin_info['id'],
            'plugin_major_version': plugin_info['version'][0],
            'plugin_minor_version': plugin_info['version'][1],
            'plugin_instance': plugin_info['instance'],
            'body': body,
        }
    ])

    print('ok', data)

    ch.basic_ack(delivery_tag=method.delivery_tag)


def main():
    parameters = pika.ConnectionParameters(
        credentials=pika.PlainCredentials(
            username='admin',
            password='admin'),
        virtual_host='node1')

    connection = pika.BlockingConnection(parameters)
    channel = connection.channel()

    queue = 'data'

    channel.queue_declare(
      queue=queue,
      durable=True)

    channel.basic_consume(message_handler, queue)
    channel.start_consuming()


if __name__ == '__main__':
    main()
