#!/usr/bin/env python3
from waggle.protocol.v0 import *


def forward_to_plugin(message):
    print('forwarding message to plugin', message)

    for datagram in unpack_datagrams(message['body']):
        print('---')
        print(datagram['plugin_id'], datagram['plugin_instance'])


dispatch_table = {
    (0, 0): forward_to_plugin, # data message type
}

body = pack_datagrams([
    {'plugin_id': 1, 'body': b'hahaha'},
    {'plugin_id': 2, 'body': b'hahaha'},
    {'plugin_id': 3, 'body': b'hahaha'},
])

data = pack_waggle_packets([{
    'sender_id': b'0123456789abcdef',
    'receiver_id': b'fedcba9876543210',
    'body': body,
}])

for message in unpack_waggle_packets(data):
    message_type = (message['message_major_type'], message['message_minor_type'])

    if message_type in dispatch_table:
        dispatch_table[message_type](message)
