#!/usr/bin/env python3
import pika
from waggle.protocol.v0 import *


def forward_datagrams_to_plugin(message):
    try:
        datagrams = unpack_datagrams(message['body'])
    except ValueError:
        print('not datagrams')
        return

    for datagram in datagrams:
        print('---')
        print(datagram['plugin_id'], datagram['plugin_instance'])
        print(datagram['body'])


dispatch_table = {
    (0, 0): forward_datagrams_to_plugin,
}


def process_message(ch, method, properties, body):
    for message in unpack_waggle_packets(body):
        message_type = (message['message_major_type'], message['message_minor_type'])

        if message_type not in dispatch_table:
            print('dropping', message)

        print('dispatch', message)
        dispatch_table[message_type](message)

    ch.basic_ack(delivery_tag=method.delivery_tag)


if __name__ == '__main__':
    parameters = pika.URLParameters('amqp://admin:testing@localhost')
    connection = pika.BlockingConnection(parameters)
    channel = connection.channel()

    channel.basic_consume(process_message, 'to-fedcba9876543210')
    channel.start_consuming()
