#!/bin/sh

export WAGGLE_NODE_ID=$(openssl x509 -in /usr/lib/waggle/SSL/node/cert.pem -noout -subject | sed 's/^.*node-\(.*\)\/.*$/\1/')
export WAGGLE_SUB_ID=0000000000000000

tmux new-session -d -s node bin/message-validator validate to-beehive'
tmux split-window -v 'bin/message-router node messages'
tmux split-window -v 'bin/message-router plugin to-sub-0000000000000000'
tmux select-layout even-vertical

tmux new-window 'run/plugin-37-0.1-1'
tmux split-window -v 'run/plugin-0-0.0-0'
tmux split-window -v 'run/plugin-1-0.0-0'
tmux select-layout even-vertical

tmux attach-session -t node
