#!/usr/bin/env python3
import pika
import time
from waggle.protocol.v0 import *


credentials = pika.PlainCredentials(
    username='admin',
    password='admin')

parameters = pika.ConnectionParameters(
    credentials=credentials,
    virtual_host='node1')

connection = pika.BlockingConnection(parameters)
channel = connection.channel()

data = pack_waggle_packets([
    {
        'sender_id': b'beehive1',
        'sender_sub_id': b'beehive1',
        'receiver_id': b'node1234',
        'receiver_sub_id': b'nc      ',
        'body': b'greetings!',
    },
])

while True:
    channel.basic_publish('', 'in-plugin-1-0.0.1-0', data)
    channel.basic_publish('', 'in-plugin-37-0.1.7-1', data)
    time.sleep(5)
