#!/usr/bin/env python3
import pika
import time
from waggle.protocol.v0 import pack_message, pack_datagram


parameters = pika.URLParameters('amqp://tester:tester@localhost')
connection = pika.BlockingConnection(parameters)
channel = connection.channel()

while True:
    text = 'Hello! This is a message from the admin! Time is {}.'.format(time.time()).encode()

    data = pack_message({
        'sender_id': '0000000000000000',
        'sender_sub_id': '0000000000000000',
        'receiver_id': '0000000000000001',
        'receiver_sub_id': '0000000000000000',
        'body': pack_datagram({
            'plugin_id': 37,
            'plugin_major_version': 0,
            'plugin_minor_version': 1,
            'plugin_instance': 1,
            'body': text,
        })
    })

    data = pack_message(
        to_id='0000000000000000',
        to_sub_id='0000000000000000',
        body=pack_datagram(
            plugin_id=37,
            plugin_major_version=0,
            plugin_minor_version=1,
            plugin_instance=1,
            body=b'hello world!'
        )
    )

    channel.basic_publish(exchange='messages', routing_key='', body=data)
    time.sleep(5)
