#!/usr/bin/env python3
import pika
import time
from waggle.protocol.v0 import *

routing_table = {
    (b'0123456789abcdef', b'fedcba9876543210'),
    (b'0123456789abcdef', b'0123456789abcdef'),
    (b'fedcba9876543210', b'fedcba9876543210'),
}


parameters = pika.URLParameters('amqp://admin:testing@localhost')
connection = pika.BlockingConnection(parameters)
channel = connection.channel()

data = pack_waggle_packets([
    {
        'sender_id': b'0123456789abcdef',
        'receiver_id': b'fedcba9876543210',
        'body': b'first!',
    },
    {
        'sender_id': b'0123456789abcdef',
        'receiver_id': b'fedcba9876543210',
        'body': b'second!',
    },
    {
        'sender_id': b'0123456789abcdef',
        'receiver_id': b'fedcba9876543210',
        'body': b'third!',
    },
    {
        'sender_id': b'0123456789abcdef',
        'receiver_id': b'fedcba9876543210',
        'body': pack_datagrams([
            {
                'plugin_id': 1,
                'body': b'hello 1',
            },
            {
                'plugin_id': 2,
                'body': b'hello 2',
            },
            {
                'plugin_id': 1,
                'plugin_instance': 1,
                'body': b'hello 3',
            },
        ]),
    },
    {
        'sender_id': b'0000000000000000',
        'receiver_id': b'0000000000000001',
        'body': pack_datagrams([
            {
                'plugin_id': 1,
                'body': b'hello 1',
            },
            {
                'plugin_id': 2,
                'body': b'hello 2',
            },
            {
                'plugin_id': 1,
                'plugin_instance': 1,
                'body': b'hello 3',
            },
        ]),
    },
])

while True:
    channel.basic_publish('', 'messages', data)
    time.sleep(3)
