#!/usr/bin/env python3
import argparse
from pipeline import Plugin
import time
import os
import pprint
import logging

logging.basicConfig(level=logging.DEBUG)

plugin = Plugin()

while True:
    # for msg in plugin.get_waiting_messages():
    #     print('run_id', plugin.run_id)
    #     print(msg)

    time.sleep(3)
    plugin.publish(b'some data to be sent')
