#!/usr/bin/env python3
import pika
import time

username = 'plugin-e5-0.1.7-1'
password = '21bfa177f9a3bd662e1d53c10ce8072ac6ac907f397d311f3993b956cf2f9a9c'

parameters = pika.ConnectionParameters(
    credentials=pika.PlainCredentials(
        username=username,
        password=password),
    virtual_host='node1')

connection = pika.BlockingConnection(parameters)
channel = connection.channel()

inqueue = 'in-{}'.format(username)
queue = 'data'

while True:
    channel.queue_declare(
        queue=inqueue,
        durable=True)

    channel.basic_publish(
        exchange='data',
        routing_key='',
        properties=pika.BasicProperties(
            delivery_mode=2,
            user_id=username),
        body=b'hello')

    time.sleep(5)
