#!/usr/bin/env python3
from pipeline import Plugin
import time

plugin = Plugin()

while True:
    for msg in plugin.get_waiting_messages():
        print(msg)

    time.sleep(3)
    plugin.publish(b'some data to be sent')
