#!/usr/bin/env python3
import argparse
import json
import os
import random
import requests
import string

SERVICE_BACKEND = os.environ.get('SERVICE_BACKEND', 'shell')

RABBITMQ_URL = 'http://localhost:15672/api'

SERVICE_TEMPLATE = '''
#!/bin/sh

export WAGGLE_PLUGIN_CREDENTIALS={credentials}

{executable}
'''

SERVICE_DIR = 'run'


def read_file(filename):
    with open(filename) as file:
        return file.read()


def read_config_file(filename):
    with open(filename) as file:
        return json.load(file)


def add_user(username, password):
    add_rabbitmq_user_with_password(username, password)
    set_rabbitmq_user_permissions(username)


def remove_user(username):
    url = RABBITMQ_URL + '/users/{}'.format(username)
    requests.delete(url, auth=('admin', 'admin'))


def add_rabbitmq_user_with_password(username, password):
    data = json.dumps({
        'name': username,
        'password': password,
        'tags': '',
    })

    url = RABBITMQ_URL + '/users/{}'.format(username)
    requests.put(url, data=data, auth=('admin', 'admin'))


def set_rabbitmq_user_permissions(username):
    inqueue = 'in-' + username

    data = json.dumps({
        'configure': '^{}$'.format(inqueue),
        'write': '^publish$',
        'read': '^{}$'.format(inqueue),
    })

    url = RABBITMQ_URL + '/permissions/{}/{}'.format('node1', username)
    requests.put(url, data=data, auth=('admin', 'admin'))


def add_service(name, credentials, executable):
    formatted = SERVICE_TEMPLATE.format(
        credentials=credentials,
        executable=executable).strip()

    os.makedirs(SERVICE_DIR, exist_ok=True)

    service_filename = os.path.join(SERVICE_DIR, name)

    with open(service_filename, 'w') as file:
        file.writelines(formatted)

    os.chmod(service_filename, 0o700)


def remove_service(name):
    try:
        os.remove(os.path.join(SERVICE_DIR, name))
    except OSError:
        pass


def get_username_for_plugin_config(config):
    return 'plugin-{}-{}-{}'.format(
        config['plugin_id'],
        config['plugin_version'],
        config['plugin_instance'])


password_characters = string.ascii_letters + string.digits


def generate_random_password():
    return ''.join(random.choice(password_characters) for _ in range(32))


def enable_plugin(plugin_dir):
    config = read_config_file(os.path.join(plugin_dir, 'plugin.json'))
    username = get_username_for_plugin_config(config)
    password = generate_random_password()
    credentials = '{}:{}'.format(username, password)
    executable = os.path.abspath(os.path.join(plugin_dir, 'plugin'))
    add_user(username, password)
    add_service(username, credentials, executable)
    print('enabled', username)


def disable_plugin(plugin_dir):
    config = read_config_file(os.path.join(plugin_dir, 'plugin.json'))
    username = get_username_for_plugin_config(config)
    remove_user(username)
    remove_service(username)
    print('disabled', username)


def main():
    parser = argparse.ArgumentParser()

    subparsers = parser.add_subparsers(dest='subcommand')

    parser_enable = subparsers.add_parser('enable')
    parser_enable.add_argument('plugin_dirs', nargs='+')

    parser_disable = subparsers.add_parser('disable')
    parser_disable.add_argument('plugin_dirs', nargs='+')

    args = parser.parse_args()

    if args.subcommand == 'enable':
        for plugin in args.plugin_dirs:
            enable_plugin(plugin)
    elif args.subcommand == 'disable':
        for plugin in args.plugin_dirs:
            disable_plugin(plugin)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
