#!/usr/bin/env python3
import waggle.plugin
import time


plugin = waggle.plugin.PrintPlugin()

while True:
    plugin.add_measurement({
        'sensor_id': 1,
        'parameter_id': 1,
        'value': b'some data',
    })

    plugin.add_measurement({
        'sensor_id': 1,
        'parameter_id': 2,
        'value': b'some more data',
    })

    plugin.add_measurement({
        'sensor_id': 2,
        'parameter_id': 1,
        'value': b'even more data',
    })

    plugin.publish_measurements()

    time.sleep(1)
