#!/usr/bin/env python3
import time
from waggle.plugin import Plugin
import waggle.protocol.v0 as protocol


plugin = Plugin()

while True:
    msg = protocol.pack_sensor_data_message([
        {'sensor_id': 1, 'parameter_id': 1, 'value': b'111'},
        {'sensor_id': 2, 'parameter_id': 2, 'value': b'222222'},
        {'sensor_id': 3, 'parameter_id': 100, 'value': b'321'},
    ])

    plugin.publish(msg)

    time.sleep(1)
