#!/usr/bin/env python3
import time
from waggle.protocol.v0.pipeline import Plugin
from waggle.protocol.v0 import *


plugin = Plugin()

while True:
    for msg in plugin.get_waiting_messages():
        print('Got a message!')
        print(msg)

    print('Sending sensor data!')

    msg = pack_sensor_message([
        {'sensor_id': 1, 'parameter_id': 1, 'value': b'111'},
        {'sensor_id': 1, 'parameter_id': 2, 'value': b'222222'},
        {'sensor_id': 232, 'parameter_id': 100, 'value': b'321'},
    ])

    plugin.publish(msg)

    print('Sending communication to node 00000001.')

    msg = pack_comm_message({
        'receiver_id': '0000000000000001',
        'receiver_sub_id': '0000000000000000',
        'body': b'hello! testing a message to another node!',
    })

    plugin.publish(msg)

    time.sleep(1)
